name: Publish Audiogram

on:
  schedule:
    - cron: '0 10 * * 4'  # giovedi alle 10:00 UTC
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Pubblica sui social
        run: |
          cd $HOME/PycharmProjects/podcast-audiogram-publisher
          .venv/bin/python -m publisher
